spring.datasource.url=jdbc:h2:mem:manadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Avoid port conflicts with frontend
server.port=8080

# Basic auth config for admin
admin.username=admin
admin.password=manadesi123

# File Upload sizes
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
